language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
os:
  - linux
install:
  - pip install --upgrade six
  - pip install .
  - pip install -r requirements/requirements-dev.txt
  - pip install -r requirements/requirements-test.txt
script: pytest tests -x -vv --cov=pipestat
after_success:
  - coveralls
branches:
  only:
    - dev
    - master
