site_name: pipestat
site_url: http://pipestat.databio.org/
site_logo: img/pipestat_logo.svg
repo_url: http://github.com/pepkit/pipestat
pypi_name: pipestat

nav:
  - Getting Started: 
    - Introduction: README.md
    - Install and configure: install.md
  - How-to guides:
    - Use Python API: python_api.md
    - Use command line interface: cli.md
  - Reference:
    - Schema specification: schema.md
    - DB config specification: db_config.md
    - Python API: autodoc_build/pipestat.md
    - Support: https://github.com/pepkit/pipestat/issues
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio

plugins:
- databio:
    jupyter_source: "docs_jupyter"
    jupyter_build: "docs_jupyter/build"
    autodoc_build: "docs/autodoc_build"
    autodoc_package: "pipestat"
    no_top_level: true
- search